title: "Dr. Dheeraj Sharan Singh | Resume"
description: "Senior Staff Data Scientist | AI & Machine Learning Leader"
url: "https://dheeraj2015.github.io"
baseurl: "/my-resume"

markdown: kramdown
theme: null
